
version: '3.7'

services:
  db:
    container_name: postgresql
    image: postgres:13-alpine
    restart: always
    env_file:
      - .env
    ports:
      - $DATABASE_PORT:$DATABASE_PORT
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      PGDATA: /data/postgresql/data/pgdata
    volumes:
      - data-volume:/data/postgresql/data

volumes:
  data-volume: